# Generated by Django 5.0.4 on 2024-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelters',
            options={'verbose_name': 'Убежищe', 'verbose_name_plural': 'Убежища'},
        ),
        migrations.AddField(
            model_name='shelters',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Свободные места'),
        ),
    ]
