# Generated by Django 5.0.4 on 2024-05-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shelters_options_shelters_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelters',
            name='imgPath',
            field=models.ImageField(upload_to='shop/static/shop/img', verbose_name='Изображение'),
        ),
    ]
