# Generated by Django 5.0.4 on 2024-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shelters_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelters',
            name='imgPath',
            field=models.ImageField(upload_to='shop/imgShelters', verbose_name='Изображение'),
        ),
    ]
