# Generated by Django 5.0.4 on 2024-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shelters_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelters',
            name='imgPath',
            field=models.ImageField(upload_to='media/imgShelters', verbose_name='Изображение'),
        ),
    ]
