# Generated by Django 4.1.10 on 2024-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shelters_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelters',
            name='imgPath',
            field=models.ImageField(upload_to='imgShelters', verbose_name='Изображение'),
        ),
    ]
