# Generated by Django 5.0.4 on 2024-06-12 03:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_reservation_usercard_reservation_user_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCard',
            new_name='UserCart',
        ),
    ]
