# Generated by Django 5.0.4 on 2024-06-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_usercard_usercart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_card',
            new_name='user_cart',
        ),
    ]
