# Generated by Django 4.1.10 on 2024-06-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shelters_imgpath'),
        ('shop', '0011_purchase'),
    ]

    operations = [
    ]
