# Generated by Django 5.0.4 on 2024-06-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
    ]
